### ISSUE TITLE
Plagiarized translation of my FluxCP

### ISSUE THREAD

**Issue by Megasantos** [HerculesWS/FluxCP#32]
I wanted to solve a problem. My translation of fluxcp was added in FluxCP hercules by JulioCF moderator without my permission, I spoke with gepard and even said he would give credit, the more he disappeared.

I believe it would be fair to give credit to me not? Because JulioCF simply copied.

my Flux: https://github.com/Megasantos/Fluxcp/blob/master/lang/pt_br.php

Flux Herc: https://github.com/HerculesWS/FluxCP/blob/master/lang/pt_br.php

**Comment by MishimaHaruna** [comment]
Gepard has since left the Hercules developer team, so I cannot answer for him. I'm not the formal administrator of this FluxCP fork either (it currently doesn't have one), but I'll intervene as the organization administrator.

First off, my apologies for the misrepresentation. I believe the translation was merged bona fide from https://github.com/JulioCF/Aeon-FluxCP/blame/master/lang/pt_br.php (committed in September 2013), but your copy is indeed older, supporting your claim.

While your file doesn't contain any copyright claims, nor it does state that the translation is yours, I am going to add a line stating `pt-br original translation courtesy of Megasantos` to the file, in apology for the misunderstanding.
Please keep in mind that this is done on a courtesy basis (rather than on a need basis). I recommend that you add a copyright line to your original file in case you want to claim copyrights for your translations in future, or at least any form of comment stating the authorship, if you don't want to enforce copyrights but simply obtain credit.
